//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.DeliveryTransactions = new HashSet<DeliveryTransaction>();
            this.Orders = new HashSet<Order>();
            this.Reviews = new HashSet<Review>();
            this.ReviewHistories = new HashSet<ReviewHistory>();
            this.SupplierAccounts = new HashSet<SupplierAccount>();
            this.SupplierProducts = new HashSet<SupplierProduct>();
            this.Transaction123Pay = new HashSet<Transaction123Pay>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string ActiveToken { get; set; }
        public string ForgotPasswordToken { get; set; }
        public int RoleId { get; set; }
        public int Status { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> TokenCreatedDate { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual Role Role { get; set; }
        public virtual Ward Ward1 { get; set; }
        public virtual ICollection<DeliveryTransaction> DeliveryTransactions { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<ReviewHistory> ReviewHistories { get; set; }
        public virtual ICollection<SupplierAccount> SupplierAccounts { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProducts { get; set; }
        public virtual ICollection<Transaction123Pay> Transaction123Pay { get; set; }
    }
}
