//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Category1 = new HashSet<Category>();
            this.Products = new HashSet<Product>();
            this.SupplierCategories = new HashSet<SupplierCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentCategoryId { get; set; }
        public int Type { get; set; }
        public int Position { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
    }
}
