//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTransaction
    {
        public DeliveryTransaction()
        {
            this.DeliveryTransactionOrders = new HashSet<DeliveryTransactionOrder>();
        }
    
        public long Id { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public string ExtraInfo { get; set; }
        public string Response { get; set; }
        public string Request { get; set; }
        public long CreatedByAccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<DeliveryTransactionOrder> DeliveryTransactionOrders { get; set; }
    }
}
