//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.DeliveryTransactionOrders = new HashSet<DeliveryTransactionOrder>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Reviews = new HashSet<Review>();
            this.Transaction123Pay = new HashSet<Transaction123Pay>();
            this.TransactionHistories = new HashSet<TransactionHistory>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double TotalPrice { get; set; }
        public string Address { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string Code { get; set; }
        public int Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<DeliveryTransactionOrder> DeliveryTransactionOrders { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Transaction123Pay> Transaction123Pay { get; set; }
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
    }
}
