//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.DealToDayCaches = new HashSet<DealToDayCache>();
            this.Discounts = new HashSet<Discount>();
            this.HomePages = new HashSet<HomePage>();
            this.Images = new HashSet<Image>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Reviews = new HashSet<Review>();
            this.SupplierProducts = new HashSet<SupplierProduct>();
        }
    
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public bool IsFeatured { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DealToDayInfo { get; set; }
        public int Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DealToDayCache> DealToDayCaches { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<HomePage> HomePages { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProducts { get; set; }
    }
}
