//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewHistory
    {
        public long Id { get; set; }
        public long ReviewId { get; set; }
        public long LastModifiedAccountId { get; set; }
        public int LastActions { get; set; }
        public string ExtraInfo { get; set; }
        public System.DateTime CreadtedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Review Review { get; set; }
    }
}
