//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.ReviewHistories = new HashSet<ReviewHistory>();
        }
    
        public long Id { get; set; }
        public string ReviewMessage { get; set; }
        public long ProductId { get; set; }
        public long OrderId { get; set; }
        public long OrderDetailId { get; set; }
        public long AccountId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ReviewHistory> ReviewHistories { get; set; }
    }
}
