//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public long Id { get; set; }
        public Nullable<long> ImageId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string GoToLink { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IOrder { get; set; }
        public int Status { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
