//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.DeliveryTransactionOrders = new HashSet<DeliveryTransactionOrder>();
            this.SupplierAccounts = new HashSet<SupplierAccount>();
            this.SupplierCategories = new HashSet<SupplierCategory>();
            this.SupplierProducts = new HashSet<SupplierProduct>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string ExraInfo { get; set; }
        public int Type { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<DeliveryTransactionOrder> DeliveryTransactionOrders { get; set; }
        public virtual ICollection<SupplierAccount> SupplierAccounts { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProducts { get; set; }
    }
}
