//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction123Pay
    {
        public long Id { get; set; }
        public string MTransactionId { get; set; }
        public string BankCode { get; set; }
        public double TotalAmount { get; set; }
        public string ClientIP { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerGender { get; set; }
        public string CustomerDOB { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerMail { get; set; }
        public string Description { get; set; }
        public long OrderId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CallbackTransactionId { get; set; }
        public string CallbackErrorCode { get; set; }
        public string CallbackDescription { get; set; }
        public string CompleteTime { get; set; }
        public string Ticket { get; set; }
        public byte Status { get; set; }
        public string ReturnCode { get; set; }
        public string Ts { get; set; }
        public string ReturnDescription { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string OpAmount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order Order { get; set; }
    }
}
