//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public int PaymentType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double TransferAmount { get; set; }
        public string ExtraInfo { get; set; }
        public int Status { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
