//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeHomePage
    {
        public TypeHomePage()
        {
            this.HomePages = new HashSet<HomePage>();
        }
    
        public long Id { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<HomePage> HomePages { get; set; }
    }
}
