//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Lib.Dal.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.DeliveryTransactionOrderDetails = new HashSet<DeliveryTransactionOrderDetail>();
            this.Reviews = new HashSet<Review>();
        }
    
        public long Id { get; set; }
        public long ProductId { get; set; }
        public long OrderId { get; set; }
        public double OriginUnitPrice { get; set; }
        public int Quantity { get; set; }
        public double Discount { get; set; }
        public int Status { get; set; }
        public int SendmailCounter { get; set; }
        public Nullable<long> DealToDayOrderId { get; set; }
    
        public virtual ICollection<DeliveryTransactionOrderDetail> DeliveryTransactionOrderDetails { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
